### ISSUE TITLE
0034. Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by BigMoWangying** [DreamWallower/leetcode#1]
自认为是二分查找，其实最坏情况还是O(n)，甚至比暴力搜索还耗时 😂 

> 难受的一匹

@DreamWallower help me！:sos:

**Comment by FongZiSing** [comment]
我看了你的代码，最坏情况是指这样的输入吗?
```
[10, 10, 10, 10, 10, 10]
10
```
平均情况是O(logN))就行了

**Comment by BigMoWangying** [comment]
> 我看了你的代码，最坏情况是指这样的输入吗?
> 
> ```
> [10, 10, 10, 10, 10, 10]
> 10
> ```
> 
> 平均情况是O(logN))就行了

I understood after seeing your code about binary search in STL thx.  :heart:
